# Generated by Django 4.1 on 2022-08-12 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MailingList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subscriber_name", models.CharField(max_length=65)),
                ("subscriber_email", models.EmailField(max_length=254)),
                ("joined", models.DateTimeField(auto_now=True)),
                (
                    "stop",
                    models.BooleanField(
                        default=False, help_text="stop receiving our emails"
                    ),
                ),
            ],
        ),
    ]
