# Generated by Django 4.1 on 2022-08-13 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailinglist",
            name="subscriber_email",
            field=models.EmailField(max_length=254, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="mailinglist",
            name="subscriber_name",
            field=models.CharField(max_length=65, verbose_name="Name "),
        ),
    ]
