# Generated by Django 4.1 on 2022-08-15 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="featured_image",
            field=models.ImageField(default="course_default.png", upload_to="courses"),
        ),
    ]
