# Generated by Django 4.1 on 2022-08-15 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_course_featured_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="featured_image",
            field=models.ImageField(
                default="courses/course_default.png", upload_to="courses"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="sub_heading",
            field=models.CharField(default="hellooo", max_length=155),
            preserve_default=False,
        ),
    ]
