# Generated by Django 4.1 on 2022-08-15 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_alter_chapter_course"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chapter",
            name="lesson_number",
        ),
        migrations.AddField(
            model_name="chapter",
            name="chapter_number_in_course",
            field=models.IntegerField(default=1, help_text="use integers"),
        ),
    ]
