# Generated by Django 4.1 on 2022-08-13 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0002_alter_lesson_author"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lesson",
            old_name="name",
            new_name="title",
        ),
    ]
